+FEATURE: Allow to import only a specific list of attributes from Akeneo and no…
oroinc/OroAkeneoBundle pull request #22
Opened 2019-08-26 07:42 UTC by sylvainraye

…t all. Use a separated value list into a specific field inside the integration settings form.

2019-10-14 16:05 UTC, dxops requested changes
Hi, @sylvainraye ,

thank you for your contribution, check my comments below please

2019-10-14 16:05 UTC, dxops commented on Entity/AkeneoSettings.php
> +    public function setAttributesList($attributeList)
Add typehint and return type please

2019-10-14 16:05 UTC, dxops commented on Form/Type/AkeneoSettingsType.php
> +            $transportData['attributesList'] = str_replace(' ','', $transportData['attributesList']);
On Akeneo side, `Attribute code may contain only letters, numbers and underscores`, so makes sense to validate attribute names also

2019-10-14 16:05 UTC, dxops commented on Integration/AkeneoTransport.php
> +     * @param null $filter
Remove this line please

2019-10-14 16:05 UTC, dxops commented on Integration/AkeneoTransport.php
> +            $attributeFilter = explode(';', str_replace(' ', '', $attrList));
It looks like `$this->transportEntity->getAttributesList()` loaded without spaces here

2019-10-14 16:05 UTC, dxops commented on Integration/Iterator/AttributeIterator.php
> +     * @param $attribute
Fix phpdoc and add return type please

2019-10-15 10:07 UTC, sylvainraye commented on Entity/AkeneoSettings.php
> +    public function setAttributesList($attributeList)
done

2019-10-15 10:07 UTC, sylvainraye commented on Form/Type/AkeneoSettingsType.php
> +            $transportData['attributesList'] = str_replace(' ','', $transportData['attributesList']);
done

2019-10-15 10:07 UTC, sylvainraye commented on Integration/AkeneoTransport.php
> +     * @param null $filter
done

2019-10-15 10:08 UTC, sylvainraye commented on Integration/AkeneoTransport.php
> +            $attributeFilter = explode(';', str_replace(' ', '', $attrList));
got issue previously, but I changed it. done

2019-10-15 10:09 UTC, sylvainraye commented on Integration/Iterator/AttributeIterator.php
> +     * @param $attribute
done

2020-01-06 13:46 UTC, dxops commented
Hello, @sylvainraye , form updates are missing, so it's not possible to create an integration.

Can we merge this PR with #24 also, to decrease code review and QA time?

2020-01-06 13:57 UTC, sylvainraye commented
Hi, yes you can

2020-01-06 14:23 UTC, dxops commented
@sylvainraye what about form fields? I get fatal errors on integration form now

2020-01-06 14:24 UTC, sylvainraye commented
What are the errors you get ?

2020-01-06 14:27 UTC, dxops commented
https://github.com/oroinc/OroAkeneoBundle/pull/22/files#diff-460e769f42ed6a8f061c31d97916f203R188-R192

child name is wrong, but I see the valid one, so will be able to fix it, thanks

2020-01-13 17:53 UTC, dxops commented
Fixed by https://github.com/oroinc/OroAkeneoBundle/commit/2a654776c0bbafb1fffc8059686fe9c8c9bf7ee7

Thanks @sylvainraye !

2020-01-13 17:53 UTC, closed without merging