Feature/merge images from child to configurable
oroinc/OroAkeneoBundle pull request #24
Opened 2019-10-07 21:14 UTC by sylvainraye

2019-10-14 17:05 UTC, dxops requested changes
Hi @sylvainraye ,

thank you for your contributions, check my comments below please

2019-10-14 17:05 UTC, dxops commented on Entity/AkeneoSettings.php
> +     * @var ParameterBagisAkeneoMergeImageToParent
Typo

2019-10-14 17:05 UTC, dxops commented on Entity/AkeneoSettings.php
> +    public function setAkeneoAttributesImageList($akeneoAttributesImageList)
Add typehint and return type please

2019-10-14 17:05 UTC, dxops commented on Entity/AkeneoSettings.php
> +    public function getAkeneoAttributesImageList(): ?string
there is no way to make $this->akeneoAttributesImageList null with typehinted setAkeneoAttributesImageList

2019-10-14 17:05 UTC, dxops commented on Form/Type/AkeneoSettingsType.php
> +            $transportData['akeneoAttributesImageList'] = str_replace(' ', '', $transportData['akeneoAttributesImageList']);
Requires validation like line above, see my comments in #22

2019-10-14 17:05 UTC, dxops commented on ImportExport/Reader/ProductImageReader.php
> +    private $attributesImageFilter = null;
Let's make it an array by default

2019-10-14 17:05 UTC, dxops commented on ImportExport/Reader/ProductImageReader.php
> +                if (null === $this->attributesImageFilter || in_array($code, $this->attributesImageFilter)) {
@sylvainraye what's the reason to add a separate field to filter image attributes?

2019-10-14 17:05 UTC, dxops commented on Integration/AkeneoTransport.php
> +        $categoryTreeChannel = null;
Create a separate PR for this fix please

2019-10-14 17:05 UTC, dxops commented on ImportExport/Reader/ProductImageReader.php
> +                            $this->proceededParent[$identifier] = true;
Can you add some description how to get the same identifier imported twice here?

2019-10-14 17:05 UTC, dxops commented on Resources/translations/messages.en.yml
> +          label: 'Merge images from children products to parent'
Update this description please
children=simple
parent=configurable

2019-10-14 17:05 UTC, dxops commented on Resources/translations/messages.en.yml
> +          tooltip: 'List of image attributes of Akeneo to use as main product picture.'
Separator and validation descriptions are missing

2019-10-14 17:05 UTC, dxops commented on ImportExport/Reader/ProductImageReader.php
> +                if (null === $this->attributesImageFilter || in_array($code, $this->attributesImageFilter)) {
Not sure that `List of image attributes of Akeneo to use as main product picture.` matches the current behavior.

This condition will skip images, but what if we have three different images for different purposes?
Main image configured in https://github.com/oroinc/OroAkeneoBundle/blob/3.1/ImportExport/DataConverter/ProductImageDataConverter.php#L15 and https://github.com/oroinc/OroAkeneoBundle/blob/3.1/ImportExport/Strategy/ProductImageImportStrategy.php#L72

2019-10-15 10:27 UTC, sylvainraye commented on ImportExport/Reader/ProductImageReader.php
> +                if (null === $this->attributesImageFilter || in_array($code, $this->attributesImageFilter)) {
`what's the reason to add a separate field to filter image attributes?`
-> In akeneo you can have many pictures for different use cases: for print, for web, for anything else. In product, those image may be at product or product model level. Currently, the connector import all pictures of a product and set them as product image which is totally a non wanted behavior and may conduct to unexpected behavior. Example, a customer may have a shop running on Magento and on OroCommerce and may need to specify three different attributes for the different sizes in Magento, while in OroCommerce only one attribute could be used. It's also relevant for project migration (for one shop system to an other), well there are many use cases indeed. Here, we give the flexibility to set which attributes should be defined as product image. 

`Not sure that List of image attributes of Akeneo to use as main product picture. matches the current behavior.`the term `main` picture is probably not appropriate, the logic here set images as Product images. It doesn't affect if an image will be a main image or a small one or else. I changed the wording. The current logic of your connector is that it takes the first image it found and set it as main product image. Which is also open for discussion regarding this logic. Hw it's an other topic that the PR doesn't cover.

2020-01-06 13:46 UTC, dxops commented
Hello, @sylvainraye , form updates are missing, so it's not possible to create an integration.

Can we merge this PR with #22 also, to decrease code review and QA time?

2020-01-06 13:55 UTC, sylvainraye commented on Entity/AkeneoSettings.php
> +    public function getAkeneoAttributesImageList(): ?string
fixed

2020-01-06 13:57 UTC, sylvainraye commented
Hi @dxops yes you can merge the PR with #22

2020-01-13 17:52 UTC, dxops commented
Fixed by https://github.com/oroinc/OroAkeneoBundle/commit/2a654776c0bbafb1fffc8059686fe9c8c9bf7ee7

2020-01-13 17:52 UTC, closed without merging